title: datascience, visualizations, training, and learning 
description: > # this means to ignore newlines until "baseurl:"
  Scientist, data scientist, blogger, trainer, learner, journey
permalink: ':title'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://manfredimiraula.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Manfredi Miraula # add your name
author-img: manfredi.jpeg # add your photo
about-author: Scientist, data enthusiast, passionate number visualizer, learner and trainer. # add description
social-instagram: phd2datascience # add your Instagram handle
social-medium: manfredimiraula # add your Instagram handle
social-twitter: manfredimiraula # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: manfredimiraula # add your Github handle
social-linkedin: manfredimiraula # add your Linkedin handle
social-email: manfredi.miraula@gmail.com# add your Email address

# Disqus
discus-identifier: manfredi-1

# Tracker
analytics: 'UA-160610044-1'

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
